# docker-compose config for testing
---
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      # critical config - kafka will not respond at
      # no host but this.
      KAFKA_ADVERTISED_HOST_NAME: kafka

  wikipedia_monitor:
    build: .
    image: wikipedia-monitor
    environment:
      KAFKA_HOST: kafka:9092
